[package]
name = "puro_boy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.8"
json = "0.12.4"
log = "0.4.27"
rand = "0.9.1"
sdl3 = "0.14.27"
